# ----------------------------------------
# 定义环境变量 (项目路径)
# ----------------------------------------
env:
  # 解决方案文件位于根目录
  SOLUTION_PATH: VideoGameCatalogue.sln
  # 后端主项目 (API/Web App) 的路径
  BACKEND_PROJECT_PATH: VideoGameCatalogue/VideoGameCatalogue.csproj
  # 后端测试项目 (单元测试) 的路径
  TEST_PROJECT_PATH: VideoGameCatalogue.Tests/VideoGameCatalogue.Tests.csproj
  # 前端客户端文件夹的路径 (Angular)
  FRONTEND_DIR: videogame-catalogue-client

steps:
- name: 1. Checkout repository
  # 检查代码到运行器
  uses: actions/checkout@v4

# ----------------------------------------
# 后端 (.NET/C#) 步骤
# ----------------------------------------
- name: 2. Setup .NET 9 SDK
  # 安装 .NET SDK
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: '9.0.x'
    
- name: 3. Restore Dependencies
  # 恢复解决方案中所有项目的 NuGet 依赖
  run: dotnet restore ${{ env.SOLUTION_PATH }}

- name: 4. Build Backend Project (Release Configuration)
  # 编译后端项目，并生成 Release 配置的二进制文件
  run: dotnet build ${{ env.BACKEND_PROJECT_PATH }} --configuration Release --no-restore

- name: 5. Run Unit Tests
  # 运行单元测试。如果任何测试失败，工作流将失败
  run: dotnet test ${{ env.TEST_PROJECT_PATH }} --configuration Debug --no-build
  
# ----------------------------------------
# 前端 (Node.js/Angular) 步骤
# ----------------------------------------
- name: 6. Setup Node.js 22
  # 安装 Node.js 运行环境
  uses: actions/setup-node@v4
  with:
    node-version: '22.x'

- name: 7. Install Frontend Dependencies (npm install)
  # 导航到前端目录并安装 npm 依赖
  run: |
    cd ${{ env.FRONTEND_DIR }}
    npm install

- name: 8. Build Frontend (npm run build)
  # 导航到前端目录并执行 Angular 编译，生成生产文件
  run: |
    cd ${{ env.FRONTEND_DIR }}
    npm run build --if-present
    
- name: 9. CI Summary
  # 所有步骤成功后的总结信息
  run: echo "Full-Stack CI/CD Workflow finished successfully!"