// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameCatalogue.Data;

#nullable disable

namespace VideoGameCatalogue.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameCatalogue.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Action-Adventure",
                            Platform = "Nintendo Switch",
                            Price = 59.99m,
                            Publisher = "Nintendo",
                            ReleaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Action RPG",
                            Platform = "PC",
                            Price = 59.99m,
                            Publisher = "FromSoftware",
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action-Adventure",
                            Platform = "PlayStation 5",
                            Price = 49.99m,
                            Publisher = "Sony Interactive Entertainment",
                            ReleaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "RPG",
                            Platform = "PC",
                            Price = 39.99m,
                            Publisher = "CD Projekt Red",
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Roguelike",
                            Platform = "Nintendo Switch",
                            Price = 24.99m,
                            Publisher = "Supergiant Games",
                            ReleaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Action-Adventure",
                            Platform = "Xbox Series X",
                            Price = 59.99m,
                            Publisher = "Rockstar Games",
                            ReleaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Simulation",
                            Platform = "PC",
                            Price = 14.99m,
                            Publisher = "ConcernedApe",
                            ReleaseDate = new DateTime(2016, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Metroidvania",
                            Platform = "PC",
                            Price = 14.99m,
                            Publisher = "Team Cherry",
                            ReleaseDate = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hollow Knight"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "RPG",
                            Platform = "PC",
                            Price = 39.99m,
                            Publisher = "CD Projekt Red",
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Sandbox",
                            Platform = "PC",
                            Price = 26.95m,
                            Publisher = "Mojang Studios",
                            ReleaseDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Action RPG",
                            Platform = "PlayStation 4",
                            Price = 39.99m,
                            Publisher = "FromSoftware",
                            ReleaseDate = new DateTime(2016, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dark Souls III"
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Platformer",
                            Platform = "Nintendo Switch",
                            Price = 19.99m,
                            Publisher = "Maddy Makes Games",
                            ReleaseDate = new DateTime(2018, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Celeste"
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Puzzle",
                            Platform = "PC",
                            Price = 9.99m,
                            Publisher = "Valve",
                            ReleaseDate = new DateTime(2011, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Portal 2"
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Action-Adventure",
                            Platform = "PC",
                            Price = 59.99m,
                            Publisher = "FromSoftware",
                            ReleaseDate = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sekiro: Shadows Die Twice"
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Simulation",
                            Platform = "Nintendo Switch",
                            Price = 59.99m,
                            Publisher = "Nintendo",
                            ReleaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Animal Crossing: New Horizons"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
